[package]
name = "sysio-rs"
version = "1.1.0"
edition = "2021"

[lib]
name = "sysio"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"]}
libc = { version = "0.2" }
